name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: tradepackage/web

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: /start
